title: "Platform Engineering Hub"
description: "A collaborative space for Platform Engineering, DevSecOps, and cloud-native best practices."
theme: jekyll-theme-cayman
markdown: kramdown
repository: codetocloudorg/platform-engineering-hub

author: "Code To Cloud Inc."
email: "info@codetocloud.io"
url: "https://www.codetocloud.io"


github_username: codetocloudorg
linkedin_username: code-to-cloud

show_downloads: false
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# baseurl: "/platform-engineering-hub" # Uncomment if needed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"