# Use the official Azure CLI image as the base
FROM mcr.microsoft.com/azure-cli:latest

# Install Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
    apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
    apt-get update && \
    apt-get install -y terraform

# Verify installations
RUN az --version && terraform --version

# Set default working directory
WORKDIR /mnt